### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by devrimgunduz** [postgrespro/pg_wait_sampling#15]
Hi,

I'm seeing a lot of useful commits after the release. In order to build RPMs for v12 and all other PostgreSQL versions, can you please release a new version?

Thanks!

Regards, Devrim

**Comment by ololobus** [comment]
Hi @devrimgunduz,

If you have no issues with current `master` I will add new release tag `v1.1.1` and try to figure out how to put this new release on PGXN. I think we should not increment second number of extension version (`1.x.0`), because there were no SQL API changes since then.

**Comment by BlackYoup** [comment]
Hello @ololobus 

I'm also interested in packaging this extension for the Exherbo distribution and have support for  PostgreSQL v12. Unfortunately I can't report any issues with current master since I did not test this extension yet.

Do you still need feedback on current master before making a release?

Thanks!

**Comment by ololobus** [comment]
Just tagged new release [v1.1.1](https://github.com/postgrespro/pg_wait_sampling/releases/tag/v1.1.1) and pushed it to PGXN as well https://pgxn.org/dist/pg_wait_sampling/

@BlackYoup @devrimgunduz, hope everything still works for you.

**Comment by anayrat** [comment]
Several version were released and are now available on yum repository https://git.postgresql.org/gitweb/?p=pgrpms.git;a=commit;h=e8090dcba30256fc9612da9da63baee4d175c155
